name: Build Posts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Run script
      run: python build_posts.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b update-posts
        git add posts/*
        git commit -m 'Update posts' || exit 0
        git push https://${{ secrets.GH_PAT }}@github.com/fantasydatapros/best-ball-data-bowl.git update-posts

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_PAT }}
        title: 'Update posts'
        body: 'Automatic update of posts'

        
