name: Build Pages

on:
  push:
    branches:
      - master  # or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert
        sudo apt-get install -y pandoc
        sudo apt-get install -y r-base
        sudo Rscript -e "install.packages('remotes', repos = 'http://cran.rstudio.com/')"
        sudo Rscript -e "install.packages('withr', repos = 'http://cran.rstudio.com/')"
        sudo Rscript -e "withr::with_libpaths(new = '/usr/local/lib/R/site-library', remotes::install_github('rstudio/rmarkdown'))"

    - name: Convert Notebooks and Rmds
      run: |
        mkdir -p dist
        for notebook in submissions/**/*.ipynb; do
            jupyter nbconvert --to html $notebook --output-dir dist
        done
        for rmd in submissions/**/*.Rmd; do
            sudo Rscript -e "withr::with_libpaths(new = '/usr/local/lib/R/site-library', rmarkdown::render('$rmd', output_dir = 'dist'))"
        done
